"""create routines table

Revision ID: 2061f17ddeec
Revises: 664c9cbbfa73
Create Date: 2025-11-24 20:04:22.135604

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2061f17ddeec'
down_revision: Union[str, Sequence[str], None] = '664c9cbbfa73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rag_documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_documents',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('doc_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('emotions', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('situations', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('embedding', Vector(1536), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rag_documents')),
    sa.UniqueConstraint('doc_id', name=op.f('uq_rag_documents_doc_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
