"""init schema

Revision ID: 29f9578ed9a5
Revises: 
Create Date: 2025-11-11 21:07:20.988856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29f9578ed9a5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('picture_url', sa.String(), nullable=True),
    sa.Column('locale', sa.String(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='세션 고유 ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='세션 소유 사용자 UUID'),
    sa.Column('message_ref_id', sa.UUID(), nullable=True, comment='세션의 원문 메시지/입력 참조 ID(옵션)'),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='세션 시작 시각'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_sessions'))
    )
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('oauth_identities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('GOOGLE', name='provider_enum'), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('raw_claims', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oauth_identities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_identities')),
    sa.UniqueConstraint('provider', 'subject', name='uq_oauth_provider_subject')
    )
    op.create_index('ix_oauth_identities_created_at', 'oauth_identities', ['created_at'], unique=False)
    op.create_index('ix_oauth_identities_user_id', 'oauth_identities', ['user_id'], unique=False)
    op.create_table('token_revocations',
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_token_revocations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('jti', name=op.f('pk_token_revocations'))
    )
    op.create_index('ix_token_revocations_revoked_at', 'token_revocations', ['revoked_at'], unique=False)
    op.create_index('ix_token_revocations_user_id', 'token_revocations', ['user_id'], unique=False)
    op.create_table('weekly_reports',
    sa.Column('weekly_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('mood_overview', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('routine_overview', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('usage_overview', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('highlights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_weekly_reports_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('weekly_id', name=op.f('pk_weekly_reports')),
    sa.UniqueConstraint('user_id', 'week_start_date', name=op.f('uq_weekly_reports_user_id_week_start_date'))
    )
    op.create_index('ix_weekly_reports_user_week_desc', 'weekly_reports', ['user_id', sa.literal_column('week_start_date DESC')], unique=False)
    op.create_table('inputs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('input_type', sa.Enum('TEXT', 'IMAGE', 'AUDIO', name='input_type_enum'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('inference_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name=op.f('fk_inputs_session_id_chat_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_inputs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inputs'))
    )
    op.create_index('ix_inputs_input_type', 'inputs', ['input_type'], unique=False)
    op.create_index('ix_inputs_session_created_at', 'inputs', ['session_id', 'created_at'], unique=False)
    op.create_index('ix_inputs_user_created_at', 'inputs', ['user_id', 'created_at'], unique=False)
    op.create_table('session_reports',
    sa.Column('report_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('highlights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mood_overview', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('routine_overview', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('usage_overview', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name=op.f('fk_session_reports_session_id_chat_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id', name=op.f('pk_session_reports')),
    sa.UniqueConstraint('session_id', name=op.f('uq_session_reports_session_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_reports')
    op.drop_index('ix_inputs_user_created_at', table_name='inputs')
    op.drop_index('ix_inputs_session_created_at', table_name='inputs')
    op.drop_index('ix_inputs_input_type', table_name='inputs')
    op.drop_table('inputs')
    op.drop_index('ix_weekly_reports_user_week_desc', table_name='weekly_reports')
    op.drop_table('weekly_reports')
    op.drop_index('ix_token_revocations_user_id', table_name='token_revocations')
    op.drop_index('ix_token_revocations_revoked_at', table_name='token_revocations')
    op.drop_table('token_revocations')
    op.drop_index('ix_oauth_identities_user_id', table_name='oauth_identities')
    op.drop_index('ix_oauth_identities_created_at', table_name='oauth_identities')
    op.drop_table('oauth_identities')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_table('users')
    # ### end Alembic commands ###
