"""upgrade_weekly_reports

Revision ID: ef6b03fc3daa
Revises: f8be0ac31754
Create Date: 2025-12-02 02:44:07.367924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef6b03fc3daa'
down_revision: Union[str, Sequence[str], None] = 'f8be0ac31754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_reports', sa.Column('week_info', sa.String(), nullable=False))
    op.add_column('weekly_reports', sa.Column('mood_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('weekly_reports', sa.Column('weekly_mood_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('weekly_reports', sa.Column('mood_manage_tip', sa.String(), nullable=False))
    op.add_column('weekly_reports', sa.Column('positive_highlights', sa.String(), nullable=False))
    op.alter_column('weekly_reports', 'routine_overview',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('weekly_reports', 'usage_overview')
    op.drop_column('weekly_reports', 'mood_overview')
    op.drop_column('weekly_reports', 'highlights')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_reports', sa.Column('highlights', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('weekly_reports', sa.Column('mood_overview', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('weekly_reports', sa.Column('usage_overview', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.alter_column('weekly_reports', 'routine_overview',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('weekly_reports', 'positive_highlights')
    op.drop_column('weekly_reports', 'mood_manage_tip')
    op.drop_column('weekly_reports', 'weekly_mood_analysis')
    op.drop_column('weekly_reports', 'mood_distribution')
    op.drop_column('weekly_reports', 'week_info')
    # ### end Alembic commands ###
