"""empty message

Revision ID: f8be0ac31754
Revises: d587dc53ce51
Create Date: 2025-12-01 23:10:26.910138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'f8be0ac31754'
down_revision: Union[str, Sequence[str], None] = 'd587dc53ce51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routines',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('routine_id', sa.Text(), nullable=False),
    sa.Column('source_doc_id', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_emotions', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('target_situations', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('routine_type', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Text(), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('environment', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('required_tools', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('steps', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('safety_notes', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('language', sa.Text(), server_default='ko', nullable=False),
    sa.Column('embedding', Vector(768), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routines')),
    sa.UniqueConstraint('routine_id', name=op.f('uq_routines_routine_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routines')
    # ### end Alembic commands ###
