"""DB_UPDATE1

Revision ID: fd45764072cf
Revises: f9dfb1ea6413
Create Date: 2025-11-26 11:01:55.936468

"""
from typing import Sequence, Union
from pgvector.sqlalchemy import Vector
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd45764072cf'
down_revision: Union[str, Sequence[str], None] = 'f9dfb1ea6413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('doc_type', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('emotions', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('situations', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('embedding', Vector(dim=1536), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rag_documents')),
    sa.UniqueConstraint('doc_id', name=op.f('uq_rag_documents_doc_id'))
    )
    op.drop_index(op.f('ix_routines_embedding'), table_name='routines', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_routines_embedding'), 'routines', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='ivfflat')
    op.drop_table('rag_documents')
    # ### end Alembic commands ###
